"""Generate ``ui/src/data/assetUniverse.js`` (the GENERATE-page asset picker) from the SSOT.

The picker must offer only **deploy-eligible** assets — assets that are both backtestable
AND on the live on-chain path — using the canonical display symbols the backend resolver
understands. Historically it was a hand-curated list that drifted: it offered single-name
equities (`AAPL`, `THYAO`, …) the SSOT holds back for compliance, mixed with ETFs. This
codegen rebuilds the picker from `universe.ON_CHAIN_SYNTHS` × `GLOBAL_ASSETS` display
symbols, grouped into user-facing buckets, so single stocks are gone and every chip
resolves on the backend (#758).

Scope note: only the GENERATE page imports this file. The EXPLORE page sources its asset
list from the backend ``/api/explore/assets`` endpoint (on-chain synth addresses via
``asset_market_service`` → ``synth_addresses``), which becomes SSOT-driven /
single-stock-free separately in #764/#765 — so this file is Generate-only and intentionally
does not cover Explore.

Usage (run from repo root; ``PYTHONPATH=backend`` makes ``archimedes`` importable since the
package lives under ``backend/`` with no top-level ``archimedes/``)::

    PYTHONPATH=backend python -m archimedes.scripts.gen_ui_asset_universe          # write the file
    PYTHONPATH=backend python -m archimedes.scripts.gen_ui_asset_universe --check  # exit 1 if the
                                                                # picker's ticker set drifts from the SSOT

NOTE: after writing, run prettier so the committed file is canonical:
    cd ui && npx prettier --write src/data/assetUniverse.js
``--check`` is **semantic** (compares the ticker set, not bytes), so prettier formatting
does not affect it.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

from archimedes.services.strategy_signal_evaluator import GLOBAL_ASSETS
from archimedes.universe import ON_CHAIN_SYNTHS

# repo-root-relative: scripts -> archimedes -> backend -> <repo root>
_OUTPUT_PATH = Path(__file__).resolve().parents[3] / "ui" / "src" / "data" / "assetUniverse.js"

# Coarse user-facing buckets → the SSOT asset_classes they cover. Order is the display order
# in the picker. Every deploy-eligible asset_class MUST appear in exactly one bucket (asserted).
_GROUPS: list[tuple[str, str, list[str]]] = [
    ("us_equity", "US equity & sectors", ["us_equity_etf", "us_sector_etf"]),
    ("intl_equity", "International equity", ["eu_equity_etf", "asia_equity_etf", "em_equity_etf", "tr_equity_etf"]),
    ("indices", "Equity indices", ["eu_index", "asia_index", "tr_index"]),
    ("crypto", "Crypto", ["crypto"]),
    ("fx", "FX", ["fx"]),
    ("metals", "Metals", ["metal_etf", "metal_eq_etf", "metal_fut"]),
    ("energy", "Energy", ["energy_etf", "energy_fut"]),
    ("agriculture", "Agriculture", ["agri_fut"]),
    (
        "fixed_income",
        "Fixed income & credit",
        [
            "us_bond_agg",
            "us_bond_long",
            "us_bond_mid",
            "us_bond_short",
            "us_bond_tbill",
            "us_bond_tips",
            "us_muni",
            "credit_ig",
            "credit_hy",
            "em_bond",
        ],
    ),
]


def _grouped() -> list[tuple[str, str, list[str]]]:
    """Return [(id, label, sorted display tickers), ...] for the deploy-eligible SSOT set."""
    # Fail loudly if _GROUPS drifts so an asset_class is mapped to more than one bucket
    # (which class_to_group below would silently collapse to the last one).
    all_classes = [cls for (_gid, _label, classes) in _GROUPS for cls in classes]
    dupes = sorted({c for c in all_classes if all_classes.count(c) > 1})
    if dupes:
        raise SystemExit(f"asset_class mapped to multiple picker groups in _GROUPS: {dupes}")
    class_to_group = {cls: gid for (gid, _label, classes) in _GROUPS for cls in classes}
    buckets: dict[str, list[str]] = {gid: [] for (gid, _l, _c) in _GROUPS}
    for synth in ON_CHAIN_SYNTHS:
        _yahoo, display, asset_class, _exch = GLOBAL_ASSETS[synth]
        gid = class_to_group.get(asset_class)
        if gid is None:
            raise SystemExit(
                f"deploy-eligible synth {synth} has asset_class {asset_class!r} not mapped to a "
                "picker group — add it to _GROUPS in gen_ui_asset_universe.py"
            )
        buckets[gid].append(display)
    return [(gid, label, sorted(buckets[gid])) for (gid, label, _classes) in _GROUPS]


def render_js() -> str:
    groups = _grouped()
    out: list[str] = []
    out.append("// AUTOGENERATED FROM backend/archimedes/data/synthetic_universe.json + GLOBAL_ASSETS.")
    out.append(
        "// DO NOT EDIT BY HAND. Regenerate from repo root: "
        "PYTHONPATH=backend python -m archimedes.scripts.gen_ui_asset_universe"
    )
    out.append("//")
    out.append("// The GENERATE-page asset picker — ONLY deploy-eligible assets (backtestable AND")
    out.append("// on the live on-chain path), using the canonical display symbols the backend's")
    out.append("// derive_asset_universe() resolves. Single-name equities are deliberately absent")
    out.append("// (held back for compliance). A CI test (test_ui_asset_universe.py) fails if this")
    out.append("// drifts from the SSOT deploy-eligible set.")
    out.append("")
    out.append("export const ASSET_GROUPS = [")
    for gid, label, assets in groups:
        out.append("  {")
        out.append(f"    id: '{gid}',")
        out.append(f"    label: '{label}',")
        rendered = ", ".join(f"'{a}'" for a in assets)
        out.append(f"    assets: [{rendered}],")
        out.append("  },")
    out.append("]")
    out.append("")
    out.append("// Flat, de-duped list of every supported display symbol (handy for validation")
    out.append("// and search). Mirrors the union of ASSET_GROUPS[*].assets.")
    out.append("export const SUPPORTED_ASSETS = Array.from(")
    out.append("  new Set(ASSET_GROUPS.flatMap((g) => g.assets)),")
    out.append(")")
    out.append("")
    out.append("export default ASSET_GROUPS")
    out.append("")
    return "\n".join(out)


def _tickers_in(js: str) -> set[str]:
    """Extract the ticker set from an assetUniverse.js (every quoted token in an assets array).

    Quote-style-insensitive: accepts both ``'...'`` and ``"..."`` (and a quoted-or-bare
    ``assets`` key) so a formatter — prettier / eslint — rewriting the generated file to double
    quotes can't make ``--check``/CI report FALSE drift (#758 review). Fails loudly if a ticker
    is duplicated ACROSS groups: a plain set would silently collapse the duplicate, so the drift
    gate would miss it even though the UI renders duplicate chips. Each display symbol must
    appear in exactly one group."""
    tickers: list[str] = []
    for block in re.findall(r"['\"]?assets['\"]?\s*:\s*\[([^\]]*)\]", js, flags=re.DOTALL):
        # (['\"]) captures the opening quote; \1 forces the SAME closing quote, so a mismatched
        # '..." can't be mis-parsed as one token.
        tickers.extend(m.group(2) for m in re.finditer(r"(['\"])([^'\"]+)\1", block))
    dupes = sorted({t for t in tickers if tickers.count(t) > 1})
    if dupes:
        raise SystemExit(
            f"duplicate ticker(s) across picker groups in assetUniverse.js: {dupes} — "
            "each display symbol must appear in exactly one group"
        )
    return set(tickers)


def expected_tickers() -> set[str]:
    return {GLOBAL_ASSETS[s][1] for s in ON_CHAIN_SYNTHS}


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    if "--check" in argv:
        if not _OUTPUT_PATH.exists():
            print(f"MISSING: {_OUTPUT_PATH} does not exist — run the generator.", file=sys.stderr)
            return 1
        got = _tickers_in(_OUTPUT_PATH.read_text(encoding="utf-8"))
        want = expected_tickers()
        if got != want:
            print(
                f"DRIFT: picker ticker set != SSOT deploy-eligible set.\n"
                f"  only-in-picker={sorted(got - want)}\n  only-in-ssot={sorted(want - got)}",
                file=sys.stderr,
            )
            return 1
        print(f"OK: picker has exactly the {len(want)} deploy-eligible tickers.")
        return 0
    _OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT_PATH.write_text(render_js(), encoding="utf-8")
    print(f"wrote {_OUTPUT_PATH} — run `cd ui && npx prettier --write src/data/assetUniverse.js`")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
