"""Generate ``docs/asset-universe.md`` from the synthetic-universe SSOT.

A human-readable, drift-proof breakdown of exactly what Archimedes prices on-chain —
rendered FROM ``backend/archimedes/data/synthetic_universe.json`` (the SSOT) so the doc
can never go stale relative to the actual universe. The on-chain deploy-eligible synths
are grouped by asset class with their oracle price and Chainlink-coverage flag; the
single-name equity synths held BACK from the live path (backtest-only, pending compliance
review) are listed separately. A test (``test_asset_universe_doc.py``) byte-diffs a fresh
render against the committed file to fail CI on stale output (#757).

Usage::

    python -m archimedes.scripts.gen_asset_universe_doc          # write the doc
    python -m archimedes.scripts.gen_asset_universe_doc --check  # exit 1 if stale (CI)
"""

from __future__ import annotations

import sys
from pathlib import Path

from archimedes.universe import (
    COMPLIANCE_FLAGGED_SINGLE_STOCKS,
    SYNTHETIC_UNIVERSE,
    chainlink_covered_synths,
)

# repo-root-relative: scripts -> archimedes -> backend -> <repo root>
_OUTPUT_PATH = Path(__file__).resolve().parents[3] / "docs" / "asset-universe.md"

# Friendly labels for the SSOT asset_class keys (anything unmapped falls back to the key).
_CLASS_LABELS = {
    "crypto": "Crypto",
    "fx": "FX",
    "us_equity_etf": "US equity ETFs",
    "us_sector_etf": "US sector ETFs",
    "eu_equity_etf": "EU equity ETFs",
    "eu_index": "EU indices",
    "asia_equity_etf": "Asia equity ETFs",
    "asia_index": "Asia indices",
    "em_equity_etf": "EM equity ETFs",
    "tr_equity_etf": "Turkish equity ETFs",
    "tr_index": "Turkish indices",
    "metal_etf": "Metal ETFs",
    "metal_eq_etf": "Metal-miner ETFs",
    "metal_fut": "Metal futures",
    "energy_etf": "Energy ETFs",
    "energy_fut": "Energy futures",
    "agri_fut": "Agricultural futures",
    "us_bond_agg": "US bonds — aggregate",
    "us_bond_long": "US bonds — long",
    "us_bond_mid": "US bonds — intermediate",
    "us_bond_short": "US bonds — short",
    "us_bond_tbill": "US bonds — T-bills",
    "us_bond_tips": "US bonds — TIPS",
    "us_muni": "US municipal bonds",
    "credit_ig": "Credit — investment grade",
    "credit_hy": "Credit — high yield",
    "em_bond": "EM bonds",
}


def _fmt_price(p: float) -> str:
    return f"${p:,.2f}"


def render_doc() -> str:
    specs = sorted(SYNTHETIC_UNIVERSE.values(), key=lambda s: s.symbol)
    covered = set(chainlink_covered_synths())
    n_total = len(specs)
    n_covered = len(covered)
    n_flagged = len(COMPLIANCE_FLAGGED_SINGLE_STOCKS)

    out: list[str] = []
    out.append("<!-- AUTOGENERATED FROM backend/archimedes/data/synthetic_universe.json — DO NOT EDIT BY HAND. -->")
    out.append("<!-- Regenerate: python -m archimedes.scripts.gen_asset_universe_doc -->")
    out.append("")
    out.append("# Archimedes asset universe")
    out.append("")
    out.append(
        "What Archimedes prices and trades on-chain. This page is **generated from the single "
        "source of truth** (`backend/archimedes/data/synthetic_universe.json`) so it can never "
        "drift from the actual universe — a CI test fails if it's stale. Regenerate with "
        "`python -m archimedes.scripts.gen_asset_universe_doc`."
    )
    out.append("")
    out.append(f"- **On-chain deploy-eligible synths:** {n_total}")
    out.append(f"- **Chainlink-covered:** {n_covered} of {n_total}")
    out.append(f"- **Single-name equity synths held back (backtest-only, compliance):** {n_flagged}")
    out.append("")
    out.append(
        "**Parity invariant:** every on-chain synth is also backtestable "
        "(`on-chain ⊆ GLOBAL_ASSETS`), and every backtestable-but-not-on-chain symbol is an "
        "explained compliance-flagged single stock. Enforced by "
        "`backend/tests/test_universe_parity.py`."
    )
    out.append("")
    out.append("## On-chain deploy-eligible universe")
    out.append("")

    by_class: dict[str, list] = {}
    for spec in specs:
        by_class.setdefault(spec.asset_class, []).append(spec)

    for asset_class in sorted(by_class, key=lambda c: _CLASS_LABELS.get(c, c).lower()):
        label = _CLASS_LABELS.get(asset_class, asset_class)
        members = sorted(by_class[asset_class], key=lambda s: s.symbol)
        out.append(f"### {label}")
        out.append("")
        out.append("| Symbol | Name | Price (USD) | Chainlink |")
        out.append("|---|---|---|---|")
        for spec in members:
            cl = "✅" if spec.chainlink_covered else "—"
            out.append(f"| `{spec.symbol}` | {spec.name} | {_fmt_price(spec.price_usd)} | {cl} |")
        out.append("")

    out.append("## Held back — single-name equities (backtest-only)")
    out.append("")
    out.append(
        "These synthetic single-name equities are **present in the backtest universe but NOT on "
        "the live on-chain path**, pending a securities/derivatives compliance review. Do not add "
        "any to the SSOT `synthetics` without sign-off."
    )
    out.append("")
    flagged = sorted(COMPLIANCE_FLAGGED_SINGLE_STOCKS)
    # Render as a wrapped inline-code list, 8 per line, for readability.
    for i in range(0, len(flagged), 8):
        out.append(" ".join(f"`{s}`" for s in flagged[i : i + 8]))
    out.append("")
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    content = render_doc()
    if "--check" in argv:
        if not _OUTPUT_PATH.exists():
            print(f"MISSING: {_OUTPUT_PATH} does not exist — run the generator.", file=sys.stderr)
            return 1
        if _OUTPUT_PATH.read_text(encoding="utf-8") != content:
            print(f"STALE: {_OUTPUT_PATH} is out of sync with the SSOT — regenerate.", file=sys.stderr)
            return 1
        print(f"OK: {_OUTPUT_PATH} is in sync with the SSOT.")
        return 0
    _OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"wrote {_OUTPUT_PATH} ({len(content.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
