"""Generate ``contracts/src/generated/SyntheticUniverse.sol`` from the synthetic-universe SSOT.

Solidity can't read JSON at runtime, so the Foundry deploy path would otherwise drift
from ``backend/archimedes/data/synthetic_universe.json`` — and it did: ``Deploy.s.sol``
hardcoded 5 synths, two of them (``sTSLA``/``sNVDA``) compliance-flagged single stocks the
SSOT deliberately removed. This codegen emits a generated Solidity library that
``Deploy.s.sol`` reads, so ``forge`` deploys exactly the SSOT set. The parity test
(``test_universe_parity.py``) regenerates and byte-diffs against the committed file to fail
CI on stale output, closing the forge-vs-SSOT gap (#756).

Usage::

    python -m archimedes.scripts.gen_solidity_universe          # write the file
    python -m archimedes.scripts.gen_solidity_universe --check  # exit 1 if stale (CI)
"""

from __future__ import annotations

import sys
from pathlib import Path

from archimedes.universe import synthetics_for_deploy

# repo-root-relative: scripts -> archimedes -> backend -> <repo root>
_OUTPUT_PATH = Path(__file__).resolve().parents[3] / "contracts" / "src" / "generated" / "SyntheticUniverse.sol"

_HEADER = """\
// SPDX-License-Identifier: MIT
// AUTOGENERATED FROM backend/archimedes/data/synthetic_universe.json — DO NOT EDIT BY HAND.
// Regenerate: python -m archimedes.scripts.gen_solidity_universe
pragma solidity ^0.8.24;

/// @title SyntheticUniverse
/// @notice On-chain synthetic universe, generated from the SSOT so the Foundry deploy
///         path (script/Deploy.s.sol) can never drift from
///         backend/archimedes/data/synthetic_universe.json. Symbols are sorted for a
///         deterministic deploy order; prices are oracle initial prices in 6-decimal USDC
///         units. Regenerate with the command above — CI (test_universe_parity.py) fails
///         on stale output.
"""


def _escape(s: str) -> str:
    # Synth names are simple ASCII ("Synthetic BTC"); guard against quotes/backslashes anyway.
    return s.replace("\\", "\\\\").replace('"', '\\"')


def render_solidity() -> str:
    """Render the generated library content. Deterministic (SSOT is sorted by symbol)."""
    synths = synthetics_for_deploy()  # sorted [(name, symbol, price_int), ...]
    n = len(synths)
    lines = [_HEADER]
    lines.append("library SyntheticUniverse {")
    lines.append(f"    uint256 internal constant COUNT = {n};")
    lines.append("")
    lines.append("    /// @return names   Synthetic display names, sorted by symbol.")
    lines.append('    /// @return symbols Synthetic symbols (e.g. "sBTC").')
    lines.append("    /// @return prices  Oracle initial prices in 6-decimal USDC units.")
    lines.append("    function synthetics()")
    lines.append("        internal")
    lines.append("        pure")
    lines.append("        returns (string[] memory names, string[] memory symbols, uint256[] memory prices)")
    lines.append("    {")
    lines.append(f"        names = new string[]({n});")
    lines.append(f"        symbols = new string[]({n});")
    lines.append(f"        prices = new uint256[]({n});")
    for i, (name, symbol, price_int) in enumerate(synths):
        lines.append(
            f'        names[{i}] = "{_escape(name)}"; symbols[{i}] = "{_escape(symbol)}"; prices[{i}] = {price_int};'
        )
    lines.append("    }")
    lines.append("}")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    content = render_solidity()
    if "--check" in argv:
        if not _OUTPUT_PATH.exists():
            print(f"MISSING: {_OUTPUT_PATH} does not exist — run the generator.", file=sys.stderr)
            return 1
        if _OUTPUT_PATH.read_text(encoding="utf-8") != content:
            print(f"STALE: {_OUTPUT_PATH} is out of sync with the SSOT — regenerate.", file=sys.stderr)
            return 1
        print(f"OK: {_OUTPUT_PATH} is in sync with the SSOT.")
        return 0
    _OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"wrote {_OUTPUT_PATH} ({len(content.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
