"""Generate ``docs/asset-universe.md`` from the synthetic-universe SSOT.

A human-readable, drift-proof breakdown of exactly what Archimedes prices on-chain —
rendered FROM ``backend/archimedes/data/synthetic_universe.json`` (the SSOT) so the doc
can never go stale relative to the actual universe. The on-chain deploy-eligible synths
are grouped by asset class with their oracle price and Chainlink-coverage flag; the
single-name equity synths held BACK from the live path (backtest-only, pending compliance
review) are listed separately. A test (``test_asset_universe_doc.py``) byte-diffs a fresh
render against the committed file to fail CI on stale output (#757).

Usage::

    python -m archimedes.scripts.gen_asset_universe_doc          # write the doc
    python -m archimedes.scripts.gen_asset_universe_doc --check  # exit 1 if stale (CI)
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from archimedes.universe import (
    COMPLIANCE_FLAGGED_SINGLE_STOCKS,
    SYNTHETIC_UNIVERSE,
    chainlink_covered_synths,
)

# repo-root-relative: scripts -> archimedes -> backend -> <repo root>
_OUTPUT_PATH = Path(__file__).resolve().parents[3] / "docs" / "asset-universe.md"
# scripts -> archimedes; the SSOT lives at archimedes/data/synthetic_universe.json
_SSOT_PATH = Path(__file__).resolve().parents[1] / "data" / "synthetic_universe.json"


def _compliance_review() -> dict[str, str]:
    """Read the SSOT ``_compliance_review`` block so the doc renders its status + reason
    VERBATIM rather than hardcoding compliance prose that could drift from the SSOT."""
    payload = json.loads(_SSOT_PATH.read_text(encoding="utf-8"))
    cr = payload.get("_compliance_review", {})
    return {"status": str(cr.get("status", "")), "reason": str(cr.get("reason", ""))}


# Friendly labels for the SSOT asset_class keys (anything unmapped falls back to the key).
_CLASS_LABELS = {
    "crypto": "Crypto",
    "fx": "FX",
    "us_equity_etf": "US equity ETFs",
    "us_sector_etf": "US sector ETFs",
    "eu_equity_etf": "EU equity ETFs",
    "eu_index": "EU indices",
    "asia_equity_etf": "Asia equity ETFs",
    "asia_index": "Asia indices",
    "em_equity_etf": "EM equity ETFs",
    "tr_equity_etf": "Turkish equity ETFs",
    "tr_index": "Turkish indices",
    "metal_etf": "Metal ETFs",
    "metal_eq_etf": "Metal-miner ETFs",
    "metal_fut": "Metal futures",
    "energy_etf": "Energy ETFs",
    "energy_fut": "Energy futures",
    "agri_fut": "Agricultural futures",
    "us_bond_agg": "US bonds — aggregate",
    "us_bond_long": "US bonds — long",
    "us_bond_mid": "US bonds — intermediate",
    "us_bond_short": "US bonds — short",
    "us_bond_tbill": "US bonds — T-bills",
    "us_bond_tips": "US bonds — TIPS",
    "us_muni": "US municipal bonds",
    "credit_ig": "Credit — investment grade",
    "credit_hy": "Credit — high yield",
    "em_bond": "EM bonds",
}


def _fmt_price(p: float) -> str:
    return f"${p:,.2f}"


def render_doc() -> str:
    # Sorted by (asset class label, symbol) so the single flat table groups naturally.
    specs = sorted(
        SYNTHETIC_UNIVERSE.values(), key=lambda s: (_CLASS_LABELS.get(s.asset_class, s.asset_class), s.symbol)
    )
    covered = set(chainlink_covered_synths())
    n_total = len(specs)
    n_covered = len(covered)
    n_not_covered = n_total - n_covered
    n_classes = len({s.asset_class for s in specs})
    n_flagged = len(COMPLIANCE_FLAGGED_SINGLE_STOCKS)
    cr = _compliance_review()

    out: list[str] = []
    out.append("<!-- AUTOGENERATED FROM backend/archimedes/data/synthetic_universe.json — DO NOT EDIT BY HAND. -->")
    out.append("<!-- Regenerate: PYTHONPATH=backend python -m archimedes.scripts.gen_asset_universe_doc -->")
    out.append("")
    out.append("# Archimedes asset universe")
    out.append("")
    out.append(
        "What Archimedes prices and trades on-chain. This page is **generated from the single "
        "source of truth** (`backend/archimedes/data/synthetic_universe.json`) so it can never "
        "drift from the actual universe — a CI test fails if it's stale. Regenerate: "
        "`PYTHONPATH=backend python -m archimedes.scripts.gen_asset_universe_doc`."
    )
    out.append("")
    out.append(f"- **On-chain deploy-eligible synths:** {n_total} across {n_classes} asset classes")
    out.append(f"- **Chainlink-covered:** {n_covered} covered · {n_not_covered} not covered (of {n_total})")
    out.append(f"- **Single-name equity synths held back (backtest-only, compliance):** {n_flagged}")
    out.append("")
    out.append(
        "**Parity invariant:** every on-chain synth is also backtestable "
        "(`on-chain ⊆ GLOBAL_ASSETS`), and every backtestable-but-not-on-chain symbol is an "
        "explained compliance-flagged single stock. Enforced by "
        "`backend/tests/test_universe_parity.py`."
    )
    out.append("")
    out.append("## On-chain deploy-eligible universe")
    out.append("")
    out.append(f"All {n_total} synths below are **on-chain-eligible** (priced on the live path).")
    out.append("")
    out.append("| Symbol | Name | Asset class | Decimals | Price (USD) | Chainlink | On-chain |")
    out.append("|---|---|---|---:|---:|:---:|:---:|")
    for spec in specs:
        label = _CLASS_LABELS.get(spec.asset_class, spec.asset_class)
        chainlink = "Yes" if spec.chainlink_covered else "No"
        out.append(
            f"| `{spec.symbol}` | {spec.name} | {label} | {spec.decimals} | "
            f"{_fmt_price(spec.price_usd)} | {chainlink} | Yes |"
        )
    out.append("")
    out.append("## Held back — single-name equities (backtest-only)")
    out.append("")
    # Status + reason rendered VERBATIM from the SSOT _compliance_review block.
    out.append(f"**Compliance status (verbatim from the SSOT):** {cr['status']}")
    out.append("")
    out.append(f"> {cr['reason']}")
    out.append("")
    out.append(
        f"The {n_flagged} single-name equity synths below are present in the backtest universe but "
        "**NOT** on the live on-chain path. Do not add any to the SSOT `synthetics` without sign-off."
    )
    out.append("")
    flagged = sorted(COMPLIANCE_FLAGGED_SINGLE_STOCKS)
    # Render as a wrapped inline-code list, 8 per line, for readability.
    for i in range(0, len(flagged), 8):
        out.append(" ".join(f"`{s}`" for s in flagged[i : i + 8]))
    out.append("")
    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    content = render_doc()
    if "--check" in argv:
        if not _OUTPUT_PATH.exists():
            print(f"MISSING: {_OUTPUT_PATH} does not exist — run the generator.", file=sys.stderr)
            return 1
        committed = _OUTPUT_PATH.read_text(encoding="utf-8")
        if committed != content:
            import difflib

            sys.stderr.writelines(
                difflib.unified_diff(
                    committed.splitlines(keepends=True),
                    content.splitlines(keepends=True),
                    fromfile="committed docs/asset-universe.md",
                    tofile="freshly generated from SSOT",
                )
            )
            print(
                f"\nSTALE: {_OUTPUT_PATH} is out of sync with the SSOT (diff above) — regenerate with "
                "`PYTHONPATH=backend python -m archimedes.scripts.gen_asset_universe_doc`.",
                file=sys.stderr,
            )
            return 1
        print(f"OK: {_OUTPUT_PATH} is in sync with the SSOT.")
        return 0
    _OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    _OUTPUT_PATH.write_text(content, encoding="utf-8")
    print(f"wrote {_OUTPUT_PATH} ({len(content.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
