"""Market models — published strategies, subscriptions, and action metering.

PublishedStrategy: A strategy that has been published by its creator via the
  Tab 1 Publish button. Each published strategy gets an isolated Type 2 Agent
  container with its own vault<>strategy mapping.

Subscription: A user's copy-trade subscription to a published strategy. Each
  subscription has its own vault (created on-chain) and an ephemeral wallet
  managed by the Arc nanopayments agent.

SubscriptionAction: Metering/consumption record for billing. Tracks each action
  the Type 3 Agent replicates from the publisher's container.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime

from sqlalchemy import Boolean, DateTime, Float, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column

from archimedes.models.chat import Base


class PublishedStrategy(Base):
    """A strategy published to the copy-trading market.

    Created when the Tab 1 Publish button completes its 7-step chain.
    """

    __tablename__ = "published_strategies"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    strategy_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    vault_address: Mapped[str] = mapped_column(String(42), nullable=False, unique=True)
    creator_address: Mapped[str] = mapped_column(String(42), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False, default="")
    metadata_json: Mapped[str] = mapped_column(Text, nullable=False, default="{}")
    # Container service names for the isolated Type 2 and Type 3 agents
    publisher_service_name: Mapped[str] = mapped_column(String(128), nullable=False, default="")
    replicator_service_name: Mapped[str] = mapped_column(String(128), nullable=False, default="")
    # Endpoint/topic that the Type 3 Agent subscribes to
    publish_endpoint: Mapped[str] = mapped_column(String(256), nullable=False, default="")
    # Funding threshold in USDC — operations gate on vault balance >= this
    funding_threshold: Mapped[float] = mapped_column(Float, nullable=False, default=10.0)
    # Status lifecycle: publishing -> live -> paused -> retired
    status: Mapped[str] = mapped_column(
        String(32), nullable=False, default="publishing", index=True
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        onupdate=lambda: datetime.now(UTC),
        nullable=False,
    )

    def get_metadata(self) -> dict:
        try:
            return json.loads(self.metadata_json)
        except (json.JSONDecodeError, TypeError):
            return {}

    def set_metadata(self, data: dict) -> None:
        self.metadata_json = json.dumps(data)

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "strategy_id": self.strategy_id,
            "vault_address": self.vault_address,
            "creator_address": self.creator_address,
            "description": self.description,
            "metadata": self.get_metadata(),
            "publisher_service_name": self.publisher_service_name,
            "replicator_service_name": self.replicator_service_name,
            "publish_endpoint": self.publish_endpoint,
            "funding_threshold": self.funding_threshold,
            "status": self.status,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }


class Subscription(Base):
    """A user's copy-trade subscription to a published strategy."""

    __tablename__ = "market_subscriptions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    published_strategy_id: Mapped[int] = mapped_column(
        Integer, nullable=False, index=True
    )
    subscriber_wallet: Mapped[str] = mapped_column(String(42), nullable=False, index=True)
    # Ephemeral wallet generated by the Arc nanopayments agent
    ephemeral_wallet_address: Mapped[str] = mapped_column(
        String(42), nullable=False, default=""
    )
    # The vault created on-chain for this subscription's funds
    vault_address: Mapped[str] = mapped_column(
        String(42), nullable=False, unique=True, default=""
    )
    # Total deposit amount in USDC
    deposit_amount: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    # Funding threshold for this specific subscription (inherited from strategy or custom)
    funding_threshold: Mapped[float] = mapped_column(Float, nullable=False, default=10.0)
    # Status lifecycle: funding -> active -> paused -> retired
    status: Mapped[str] = mapped_column(
        String(32), nullable=False, default="funding", index=True
    )
    # Arc agent payment reference
    arc_payment_ref: Mapped[str] = mapped_column(String(128), nullable=False, default="")
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(UTC),
        onupdate=lambda: datetime.now(UTC),
        nullable=False,
    )

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "published_strategy_id": self.published_strategy_id,
            "subscriber_wallet": self.subscriber_wallet,
            "ephemeral_wallet_address": self.ephemeral_wallet_address,
            "vault_address": self.vault_address,
            "deposit_amount": self.deposit_amount,
            "funding_threshold": self.funding_threshold,
            "status": self.status,
            "arc_payment_ref": self.arc_payment_ref,
            "created_at": self.created_at.isoformat() if self.created_at else None,
            "updated_at": self.updated_at.isoformat() if self.updated_at else None,
        }


class SubscriptionAction(Base):
    """Metering/consumption record for a subscription.

    Records each action the Type 3 Agent replicates, used for billing/metering.
    The exact metering schema is not fully specified upstream — this is a
    minimal implementation tracking action type and timestamp per subscription.
    """

    __tablename__ = "subscription_actions"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    subscription_id: Mapped[int] = mapped_column(
        Integer, nullable=False, index=True
    )
    action_type: Mapped[str] = mapped_column(String(64), nullable=False)
    action_data: Mapped[str] = mapped_column(Text, nullable=False, default="{}")
    recorded_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(UTC), nullable=False
    )

    def get_action_data(self) -> dict:
        try:
            return json.loads(self.action_data)
        except (json.JSONDecodeError, TypeError):
            return {}

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "subscription_id": self.subscription_id,
            "action_type": self.action_type,
            "action_data": self.get_action_data(),
            "recorded_at": self.recorded_at.isoformat() if self.recorded_at else None,
        }
