import { defineConfig, presetUno, presetIcons } from 'unocss'
import cryptoColorIcons from '@iconify-json/cryptocurrency-color/icons.json'
import simpleIcons from '@iconify-json/simple-icons/icons.json'
import logosIcons from '@iconify-json/logos/icons.json'
import tokenBrandedIcons from '@iconify-json/token-branded/icons.json'

export default defineConfig({
  // preflights: [],
  presets: [
    presetUno({ preflight: false }),
    presetIcons({
      collections: {
        'cryptocurrency-color': () => cryptoColorIcons,
        'simple-icons': () => simpleIcons,
        'logos': () => logosIcons,
        'token-branded': () => tokenBrandedIcons,
      },
      scale: 1,
      extraProperties: { display: 'inline-block', 'vertical-align': 'middle' },
    }),
  ],
  theme: {
    colors: {
      accent:   '#D4A853',
      canvas:   '#09090B',
      surface1: '#0F0F12',
      surface2: '#16161A',
      surface3: '#1C1C21',
      text1:    '#FAFAFA',
      text2:    '#A1A1AA',
      text3:    '#71717A',
      positive: '#22C55E',
      negative: '#EF4444',
    },
    fontFamily: {
      sans:  'var(--sans)',
      serif: 'var(--serif)',
      mono:  'var(--mono)',
    },
    breakpoints: {
      sm:  '600px',
      md:  '768px',
      lg:  '1024px',
      xl:  '1280px',
    },
  },
  // Ensure dynamic icon classes are generated
  safelist: [
    'i-lucide-file-text',
    'i-lucide-link',
    'i-lucide-bot',
    'i-lucide-lock',
    'i-lucide-wallet',
    'i-lucide-circle-dollar-sign',
    'i-lucide-scroll-text',
    'i-lucide-arrow-left-right',
    'i-lucide-zap',
    'i-lucide-radio',
    'i-lucide-flask-conical',
    'i-lucide-layers',
    'i-lucide-check',
    'i-lucide-check-circle',
    'i-lucide-circle',
    'i-lucide-chevron-up',
    'i-lucide-chevron-down',
    'i-lucide-alert-triangle',
    'i-lucide-arrow-up-down',
    'i-lucide-droplet',
    'i-lucide-layers',
    'i-lucide-star',
    'i-lucide-trophy',
    'i-lucide-users',
    'i-lucide-trending-up',
    'i-lucide-coins',
    'i-lucide-fuel',
    'i-lucide-bar-chart-2',
    'i-lucide-globe',
    'i-lucide-flame',
    'i-lucide-scale',
    'i-lucide-palette',
    'i-lucide-user',
    'i-lucide-message-circle',
    'i-lucide-send',
    'i-lucide-loader',
    'i-lucide-anchor',
    'i-lucide-search',
    'i-lucide-brain',
    'i-lucide-x-circle',
    'i-lucide-target',
    'i-lucide-x',
    'i-lucide-trending-down',
    'i-lucide-vault',
    'i-lucide-activity',
    'i-lucide-refresh-cw',
    'i-lucide-minus',
    'i-lucide-home',
    'i-lucide-compass',
    'i-lucide-line-chart',
    'i-lucide-layout-dashboard',
    'i-lucide-plus-square',
    'i-lucide-shield-alert',
    'i-lucide-library',
    'i-lucide-panel-left-close',
    'i-lucide-panel-left-open',
    'i-lucide-arrow-left',
    'i-lucide-chevron-right',
    'i-lucide-check-circle-2',
    'i-lucide-sparkles',
    'i-lucide-graduation-cap',
    // Crypto asset logos
    'i-cryptocurrency-color-btc',
    'i-cryptocurrency-color-usdc',
    // Brand logos
    'i-simple-icons-tesla',
    'i-simple-icons-nvidia',
    'i-simple-icons-coinbase',
    'i-logos-metamask',
    'i-token-branded-metamask',
  ],
})
